### ISSUE TITLE
Can/should we remove the .ipynb_checkpoints from the examples directory?

### ISSUE THREAD

**Issue by kybowm** [sassoftware/python-cvpy#59]
It looks like all the files [in the examples/.ipynb_checkpoints]( https://github.com/sassoftware/python-cvpy/tree/main/examples/.ipynb_checkpoints) are also included [in examples/biomedimage](https://github.com/sassoftware/python-cvpy/tree/main/examples/biomedimage) with no meaningful differences. (When I run diff, the checkpoint has a new line and a comment "# Connect to the SAS CAS Server\n." Otherwise no differences.)

If it's not needed, I think it's a cleaner to remove it, but I don't want to remove anything that might have a purpose.

@courtneyambrozic , what do you think?

**Comment by courtneyambrozic** [comment]
Yes, absolutely! I'm not really sure why I added those in the first place and have been meaning to remove them. Thanks for the cleanup, @kybowm!

**Comment by kybowm** [comment]
Closed with #60
